let profiles=[]; let settings={}; let prompts=[]; let currentPage='video';
const $=s=>document.querySelector(s); const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function init(){profiles=await glabs.listProfiles();settings=await glabs.getSettings();render(); updateStats();}
function render(){document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===currentPage));$('#title').textContent=currentPage==='video'?'Flow Video':currentPage==='accounts'?'Tài khoản Flow':currentPage==='logs'?'Log Chi Tiết':currentPage; if(currentPage==='video') renderVideo(); else if(currentPage==='accounts') renderAccounts(); else if(currentPage==='logs') renderLogs(); else renderPlaceholder();}
function renderVideo(){ $('#content').innerHTML=`<div class="tabs"><button class="active">Văn bản → Video</button><button>Ảnh / Video thành phần → Video</button><button>Nối cảnh → Video</button></div><div class="grid"><div class="card"><div class="field"><label>Model</label><select id="model"><option>Veo 3.1</option><option>Gemini Omni Flash</option></select></div><div class="field"><label>Tỷ lệ video</label><select id="ratio"><option>9:16</option><option>16:9</option><option>1:1</option></select></div><div class="field"><label>Thời lượng</label><select id="duration"><option>8s</option><option>6s</option><option>4s</option></select></div><div class="field"><label>Ngưỡng credit tự đổi tài khoản</label><input id="minCredits" type="number" value="${settings.minCredits||10}"></div><div class="field"><label>Thời gian chờ giữa prompt (ms)</label><input id="waitBetween" type="number" value="${settings.waitBetween||2000}"></div><button class="btn" id="saveSettings">Lưu cấu hình</button></div><div class="card"><div class="field"><label>Prompt</label><textarea id="prompt" placeholder="Dán prompt tại đây..."></textarea></div><div class="toolbar"><button class="btn" id="add">+ Thêm vào hàng đợi</button><button class="btn" id="import">Nhập TXT</button><button class="btn" id="run">▶ Chạy ngay</button><button class="btn" id="stop">■ Dừng</button></div><div class="queue" id="queue"></div></div></div>`; $('#add').onclick=addPrompt;$('#run').onclick=run;$('#stop').onclick=()=>glabs.stopQueue();$('#saveSettings').onclick=saveSettings; $('#import').onclick=()=>alert('Bản EXE sẽ có hộp chọn TXT/Excel. Bản mã nguồn này giữ Queue dạng textarea để kiểm thử nhanh.'); renderQueue(); }
function addPrompt(){const v=$('#prompt').value.trim();if(!v)return;prompts.push(v);$('#prompt').value='';renderQueue();updateStats();}
function renderQueue(){const q=$('#queue');if(!q)return;q.innerHTML=prompts.map((p,i)=>`<div class="task"><b>${i+1}.</b> ${esc(p)}<small>QUEUED</small></div>`).join('')||'<small>Chưa có prompt trong hàng đợi.</small>';}
async function saveSettings(){settings={...settings,model:$('#model').value,duration:$('#duration').value,ratio:$('#ratio').value,minCredits:Number($('#minCredits').value),waitBetween:Number($('#waitBetween').value)};await glabs.setSettings(settings);alert('Đã lưu.');}
async function run(){if(!prompts.length){alert('Hàng đợi đang trống.');return}await saveSettings();const ps=profiles.filter(p=>p.enabled);if(!ps.length){alert('Chưa có Chrome Profile. Vào Tài khoản Flow để thêm và đăng nhập.');return}await glabs.runQueue({prompts:[...prompts],profiles:ps,settings});}
function renderAccounts(){ $('#content').innerHTML=`<div class="card"><div class="toolbar"><button class="btn primary" id="addProfile">+ Thêm tài khoản</button><button class="btn" id="openFolder">Mở thư mục Profiles</button></div><p><small>Đăng nhập thủ công trong từng Chrome Profile. Tool không nhập hoặc lưu mật khẩu.</small></p>${profiles.map(p=>`<div class="account"><b>${p.id}</b><div><b>${esc(p.name)}</b><div><small>${esc(p.path)}</small></div></div><span class="pill ${p.status==='ĐÃ ĐĂNG NHẬP'?'ok':''}">${esc(p.status||'CHƯA ĐĂNG NHẬP')}</span><div class="row"><button class="btn login" data-id="${p.id}">Đăng nhập / Mở</button><button class="btn remove" data-id="${p.id}">Xóa</button></div></div>`).join('')}</div>`;$('#addProfile').onclick=async()=>{const n=prompt('Tên Gmail/profile:');if(n){await glabs.addProfile(n);profiles=await glabs.listProfiles();renderAccounts();updateStats()}};$('#openFolder').onclick=()=>glabs.openFolder('profiles');document.querySelectorAll('.login').forEach(b=>b.onclick=async()=>{await glabs.loginProfile(b.dataset.id);});document.querySelectorAll('.remove').forEach(b=>b.onclick=async()=>{if(confirm('Xóa profile khỏi danh sách?')){await glabs.removeProfile(b.dataset.id);profiles=await glabs.listProfiles();renderAccounts();updateStats()}});}
function renderLogs(){$('#content').innerHTML='<div class="card"><div id="logs" class="logbox"></div></div>';}
function renderPlaceholder(){$('#content').innerHTML='<div class="card"><h2>Module</h2><p>Khung module sẵn sàng để mở rộng. Flow Video và Tài khoản Flow là module hoạt động của bản đầu tiên.</p></div>';}
function updateStats(){$('#sAccounts').textContent=profiles.length;}
glabs.on('state',s=>{ $('#sRunning').textContent=s.running||0;$('#sQueue').textContent=s.queued||0;$('#sDone').textContent=s.done||0;$('#sError').textContent=s.errors||0; });
glabs.on('log',x=>{const l=$('#logs');if(l){l.textContent+=`[${x.time}] ${x.message} ${JSON.stringify(x)}\n`;l.scrollTop=l.scrollHeight;}});
document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>{currentPage=b.dataset.page;render()});
init();
